# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
{{ if and .Values.externalSecretsOperator.enabled .Values.global.awsRegion }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.lfx.namespace }}
spec:
  refreshInterval: "{{ .Values.externalSecretsOperator.externalSecret.refreshInterval }}"
  secretStoreRef:
    name: {{ .Chart.Name }}
    kind: SecretStore
  target:
    name: {{ .Chart.Name }}
    creationPolicy: Owner
    deletionPolicy: Retain
  {{- if .Values.externalSecretsOperator.externalSecret.data }}
  data:
    {{- range .Values.externalSecretsOperator.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        {{- if .remoteRef.property }}
        property: {{ .remoteRef.property }}
        {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
