# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
{{- if .Values.heimdall.enabled }}
apiVersion: heimdall.dadrus.github.com/v1alpha4
kind: RuleSet
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.lfx.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  authClassName: default
  rules:
    - id: "rule:lfx:lfx-v2-survey-service:surveys:schedule"
      match:
        methods:
          - POST
        routes:
          - path: /surveys
      allow_encoded_slashes: "off"
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: json_content_type
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "committee:{{ "{{- .Request.Body.committee_uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests
          (Only meant for *local development* because OpenFGA should be enabled when deployed)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-survey-service:surveys:get"
      match:
        methods:
          - GET
        routes:
          - path: /surveys/:survey_uid
      allow_encoded_slashes: "off"
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: viewer
              object: "survey:{{ "{{- .Request.URL.Captures.survey_uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests
          (Only meant for *local development* because OpenFGA should be enabled when deployed)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-survey-service:surveys:update"
      match:
        methods:
          - PUT
        routes:
          - path: /surveys/:survey_uid
      allow_encoded_slashes: "off"
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "survey:{{ "{{- .Request.URL.Captures.survey_uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests
          (Only meant for *local development* because OpenFGA should be enabled when deployed)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-survey-service:surveys:delete"
      match:
        methods:
          - DELETE
        routes:
          - path: /surveys/:survey_uid
      allow_encoded_slashes: "off"
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "survey:{{ "{{- .Request.URL.Captures.survey_uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests
          (Only meant for *local development* because OpenFGA should be enabled when deployed)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-survey-service:surveys:bulk_resend"
      match:
        methods:
          - POST
        routes:
          - path: /surveys/:survey_uid/bulk_resend
      allow_encoded_slashes: "off"
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "survey:{{ "{{- .Request.URL.Captures.survey_uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests
          (Only meant for *local development* because OpenFGA should be enabled when deployed)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-survey-service:surveys:preview_send"
      match:
        methods:
          - GET
        routes:
          - path: /surveys/:survey_uid/preview_send
      allow_encoded_slashes: "off"
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: auditor
              object: "survey:{{ "{{- .Request.URL.Captures.survey_uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests
          (Only meant for *local development* because OpenFGA should be enabled when deployed)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-survey-service:surveys:send_missing_recipients"
      match:
        methods:
          - POST
        routes:
          - path: /surveys/:survey_uid/send_missing_recipients
      allow_encoded_slashes: "off"
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "survey:{{ "{{- .Request.URL.Captures.survey_uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests
          (Only meant for *local development* because OpenFGA should be enabled when deployed)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-survey-service:surveys:responses:delete"
      match:
        methods:
          - DELETE
        routes:
          - path: /surveys/:survey_uid/responses/:response_id
      allow_encoded_slashes: "off"
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "survey:{{ "{{- .Request.URL.Captures.survey_uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests
          (Only meant for *local development* because OpenFGA should be enabled when deployed)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-survey-service:surveys:responses:resend"
      match:
        methods:
          - POST
        routes:
          - path: /surveys/:survey_uid/responses/:response_id/resend
      allow_encoded_slashes: "off"
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "survey:{{ "{{- .Request.URL.Captures.survey_uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests
          (Only meant for *local development* because OpenFGA should be enabled when deployed)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-survey-service:surveys:recipient_group:delete"
      match:
        methods:
          - DELETE
        routes:
          - path: /surveys/:survey_uid/recipient_group
      allow_encoded_slashes: "off"
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "survey:{{ "{{- .Request.URL.Captures.survey_uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests
          (Only meant for *local development* because OpenFGA should be enabled when deployed)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-survey-service:surveys:exclusion:create"
      match:
        methods:
          - POST
        routes:
          - path: /surveys/exclusion
      allow_encoded_slashes: "off"
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: member
              object: "team:global_survey_platform_admins"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests
          (Only meant for *local development* because OpenFGA should be enabled when deployed)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-survey-service:surveys:exclusion:delete"
      match:
        methods:
          - DELETE
        routes:
          - path: /surveys/exclusion
      allow_encoded_slashes: "off"
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: member
              object: "team:global_survey_platform_admins"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests
          (Only meant for *local development* because OpenFGA should be enabled when deployed)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-survey-service:surveys:exclusion:get"
      match:
        methods:
          - GET
        routes:
          - path: /surveys/exclusion/:exclusion_id
      allow_encoded_slashes: "off"
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: member
              object: "team:global_survey_platform_admins"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests
          (Only meant for *local development* because OpenFGA should be enabled when deployed)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-survey-service:surveys:exclusion:delete_by_id"
      match:
        methods:
          - DELETE
        routes:
          - path: /surveys/exclusion/:exclusion_id
      allow_encoded_slashes: "off"
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: member
              object: "team:global_survey_platform_admins"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests
          (Only meant for *local development* because OpenFGA should be enabled when deployed)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-survey-service:surveys:validate_email"
      match:
        methods:
          - POST
        routes:
          - path: /surveys/validate_email
      allow_encoded_slashes: "off"
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: member
              object: "team:global_survey_platform_admins"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests
          (Only meant for *local development* because OpenFGA should be enabled when deployed)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}
{{- end }}
