# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
{{- if .Values.heimdall.enabled }}
apiVersion: heimdall.dadrus.github.com/v1alpha4
kind: RuleSet
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.lfx.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  authClassName: default
  rules:
    - id: "rule:lfx:lfx-v2-survey-service:surveys:create"
      match:
        methods:
          - POST
        routes:
          - path: /surveys
      allow_encoded_slashes: "off"
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: json_content_type
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "project:{{ "{{- .Request.Body.project_uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests
          (Only meant for *local development* because OpenFGA should be enabled when deployed)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-survey-service:surveys:survey:get"
      match:
        methods:
          - GET
        routes:
          - path: /surveys/:id
      allow_encoded_slashes: "off"
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: viewer
              object: "survey:{{ "{{- .Request.URL.Captures.id -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests
          (Only meant for *local development* because OpenFGA should be enabled when deployed)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-survey-service:surveys:survey:update"
      match:
        methods:
          - PUT
        routes:
          - path: /surveys/:id
      allow_encoded_slashes: "off"
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "survey:{{ "{{- .Request.URL.Captures.id -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests
          (Only meant for *local development* because OpenFGA should be enabled when deployed)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-survey-service:surveys:survey:delete"
      match:
        methods:
          - DELETE
        routes:
          - path: /surveys/:id
      allow_encoded_slashes: "off"
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "survey:{{ "{{- .Request.URL.Captures.id -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests
          (Only meant for *local development* because OpenFGA should be enabled when deployed)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-survey-service:surveys:survey:extend"
      match:
        methods:
          - POST
        routes:
          - path: /surveys/:id/extend
      allow_encoded_slashes: "off"
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "survey:{{ "{{- .Request.URL.Captures.id -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests
          (Only meant for *local development* because OpenFGA should be enabled when deployed)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-survey-service:surveys:survey:enable"
      match:
        methods:
          - PUT
        routes:
          - path: /surveys/:id/enable
      allow_encoded_slashes: "off"
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "survey:{{ "{{- .Request.URL.Captures.id -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests
          (Only meant for *local development* because OpenFGA should be enabled when deployed)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-survey-service:surveys:survey:bulk_resend"
      match:
        methods:
          - POST
        routes:
          - path: /surveys/:id/bulk_resend
      allow_encoded_slashes: "off"
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "survey:{{ "{{- .Request.URL.Captures.id -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests
          (Only meant for *local development* because OpenFGA should be enabled when deployed)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-survey-service:surveys:survey:results"
      match:
        methods:
          - GET
        routes:
          - path: /surveys/:id/results
      allow_encoded_slashes: "off"
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: results_viewer
              object: "survey:{{ "{{- .Request.URL.Captures.id -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests
          (Only meant for *local development* because OpenFGA should be enabled when deployed)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-survey-service:survey_response:create"
      match:
        methods:
          - POST
        routes:
          - path: /survey_responses
      allow_encoded_slashes: "off"
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: json_content_type
        - authorizer: openfga_check
          config:
            values:
              relation: participant
              object: "survey:{{ "{{- .Request.Body.survey_uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests
          (Only meant for *local development* because OpenFGA should be enabled when deployed)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-survey-service:survey_response:get"
      match:
        methods:
          - GET
        routes:
          - path: /survey_responses/:id
      allow_encoded_slashes: "off"
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: auditor
              object: "survey_response:{{ "{{- .Request.URL.Captures.id -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests
          (Only meant for *local development* because OpenFGA should be enabled when deployed)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-survey-service:survey_response:update"
      match:
        methods:
          - PUT
        routes:
          - path: /survey_responses/:id
      allow_encoded_slashes: "off"
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: owner
              object: "survey_response:{{ "{{- .Request.URL.Captures.id -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests
          (Only meant for *local development* because OpenFGA should be enabled when deployed)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-survey-service:survey_response:resend"
      match:
        methods:
          - POST
        routes:
          - path: /survey_responses/:id/resend
      allow_encoded_slashes: "off"
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "survey:{{ "{{- .Request.URL.Captures.id -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests
          (Only meant for *local development* because OpenFGA should be enabled when deployed)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}
{{- end }}
