# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
{{ if and .Values.externalSecretsOperator.enabled .Values.global.awsRegion }}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.lfx.namespace }}
spec:
  provider:
    aws:
      service: "SecretsManager"
      region: {{ .Values.global.awsRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccount.name | default .Chart.Name }}
{{- end }}
