# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
apiVersion: v2
name: lfx-v2-survey-service
description: LFX Platform V2 Survey Service chart
type: application
# This version should not be incremented, as it is dynamically replaced with the release version during the chart build job.
version: 0.0.1
appVersion: "latest"
