# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
apiVersion: v2
name: lfx-v2-survey-service
description: LFX Platform V2 Survey Service chart
type: application
version: 0.1.2
appVersion: "latest"
