# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
name: "Survey API Build"

"on": [pull_request]

permissions:
  contents: read

jobs:
  build-pr:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Setup go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: go.mod

      - name: Download Dependencies
        run: make deps

      - name: Generate service code
        run: make apigen

      - name: Build
        run: make build

      - name: Test
        run: go test ./... -v
